### ISSUE TITLE
Error trying to parse non-json response from sendinblue

### ISSUE THREAD

**Issue by DanielEvolufarma** [mailin-api/sendinblue-nodejs-api-npm#14]
Seems like sendinblue is trying to do a JSON.parse without a try/catch block, so if the response is not JSON, it just fails without popping out the actual response from the server. Code in sendinblue-api/sendinblue-api.js line 32.

Attached error:
`2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR SyntaxError: Unexpected token < in JSON at position 0
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at JSON.parse (<anonymous>)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at Request.<anonymous> (/home/vcap/app/node_modules/sendinblue-api/sendinblue-api.js:32:27)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at emitTwo (events.js:126:13)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at Request.emit (events.js:214:7)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at Request._fireSuccess (/home/vcap/app/node_modules/restler/lib/restler.js:229:10)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at /home/vcap/app/node_modules/restler/lib/restler.js:161:20
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at Request._encode (/home/vcap/app/node_modules/restler/lib/restler.js:200:9)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at /home/vcap/app/node_modules/restler/lib/restler.js:157:16
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at Request._decode (/home/vcap/app/node_modules/restler/lib/restler.js:173:7)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/restler/lib/restler.js:150:14)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at emitNone (events.js:111:20)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at IncomingMessage.emit (events.js:208:7)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at endReadableNT (_stream_readable.js:1064:12)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at /home/vcap/app/node_modules/async-listener/glue.js:188:31
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-09-25T19:52:26.81+0200 [APP/PROC/WEB/0]ERR     at process._tickCallback (internal/process/next_tick.js:180:9)
`

Attached code that needs at least a try/catch

`restler.request(called_url, {method: method, timeout: this.timeout, data: input, headers: {'api-key': this.api_key, 'content-type': content_type}})
	.on('timeout', function(ms){
		cb('Request timed out within '+ms+' MS', null);
	})
	.on('complete', function(response) {
		if (response instanceof Error) {
			cb("Request Failed", null);
		} else {
			**var responseObj = JSON.parse(response);**
			cb(null, responseObj);
		}
	});`

Thanks

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-nodejs-library
