### ISSUE TITLE
cb is not a funcation 

### ISSUE THREAD

**Issue by vishnumishra** [mailin-api/sendinblue-nodejs-api-npm#2]
node_modules/sendinblue-api/sendinblue-api.js:734

```
return cb(null, result);
       ^
```

TypeError: cb is not a function

at /node_modules/sendinblue-api/sendinblue-api.js:734:10
at /node_modules/sendinblue-api/sendinblue-api.js:46:10
at Request.<anonymous> (/node_modules/sendinblue-api/sendinblue-api.js:28:3)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request.mixin._fireSuccess (/node_modules/restler/lib/restler.js:229:10)
at /node_modules/restler/lib/restler.js:161:20
at Request.mixin._encode (/node_modules/restler/lib/restler.js:200:9)
at /node_modules/restler/lib/restler.js:157:16
at Gunzip.onEnd (zlib.js:227:5)
at emitNone (events.js:72:20)
at Gunzip.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:905:12)
at nextTickCallbackWith2Args (node.js:441:9)
at process._tickDomainCallback (node.js:396:17)

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.

Our SendinBlue APIs NPM package support node callbacks.
If you do not prefer callbacks, you can use our simpler node.js API wrapper: https://github.com/mailin-api/mailin-api-node-js

Regards,
SendinBlue Team
