### ISSUE TITLE
Unexpected end of JSON from docs example

### ISSUE THREAD

**Issue by patrickbolle** [mailin-api/sendinblue-nodejs-api-npm#5]
Hi there.
Need to get sendinblue working for a client this week.
Using the example docs from here - https://github.com/mailin-api/sendinblue-nodejs-api-npm/blob/master/examples/send_email.js

Which I saw was suggested in a past issue.
Errors I'm getting : 
```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request.<anonymous> (/home/patrick/Programming/shiok-waiting/server/node_modules/sendinblue-api/sendinblue-api.js:29:26)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (/home/patrick/Programming/shiok-waiting/server/node_modules/restler/lib/restler.js:229:10)
    at /home/patrick/Programming/shiok-waiting/server/node_modules/restler/lib/restler.js:161:20
    at Request._encode (/home/patrick/Programming/shiok-waiting/server/node_modules/restler/lib/restler.js:200:9)
    at /home/patrick/Programming/shiok-waiting/server/node_modules/restler/lib/restler.js:157:16
    at Request._decode (/home/patrick/Programming/shiok-waiting/server/node_modules/restler/lib/restler.js:173:7)
    at IncomingMessage.<anonymous> (/home/patrick/Programming/shiok-waiting/server/node_modules/restler/lib/restler.js:150:14)
```

I've tried everything, reformatting my JSON, rebuilding app, etc - no luck.

Any help here?

**Comment by ekta-slit** [comment]
Hello @patrickbolle 

Thank you for contacting us.

The sample ( https://github.com/mailin-api/sendinblue-nodejs-api-npm/blob/master/examples/send_email.js ) works as expected.
There was a temporay issue at our end which lead to this error.
We had added error handling in wrapper.

Please update the package :)


Regards
SendinBlue Team
